version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
          MYSQL_DATABASE: circle_test
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: Waiting for Mysql to be ready
          command: |
            for i in `seq 1 50`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Mysql && exit 1
      - run:
          name: run test
          environment:
            MYSQL_DB_URL: "mysql://root:root@/circle_test?charset=utf8&parseTime=True&loc=Local"
          command: yarn test
